import type { BusinessCategory } from '@/lib/categories'
import type { IncheonDataSource } from './types'

export const INCHEON_PRODUCT_MODE = 'openrisk-incheon' as const
export const INCHEON_DATA_POLICY = 'public-data-only' as const
export const INCHEON_RADIUS_METERS = 500
export const INCHEON_H3_RESOLUTION = 10

export const INCHEON_BOUNDS = {
  latMin: 37.30,
  latMax: 37.65,
  lngMin: 126.35,
  lngMax: 126.95,
}

export const INCHEON_DEMO_LOCATIONS: Record<string, { label: string; lat: number; lng: number }> = {
  songdo: { label: '인천 연수구 송도동', lat: 37.3897, lng: 126.6454 },
  bupyeong: { label: '인천 부평구 부평역', lat: 37.4895, lng: 126.7247 },
  guwol: { label: '인천 남동구 구월동', lat: 37.4488, lng: 126.7016 },
  cheongna: { label: '인천 서구 청라동', lat: 37.5329, lng: 126.6508 },
  geomdan: { label: '인천 서구 검단', lat: 37.5941, lng: 126.6675 },
  yeongjong: { label: '인천 중구 영종도', lat: 37.4946, lng: 126.5365 },
  juan: { label: '인천 미추홀구 주안역', lat: 37.4649, lng: 126.6799 },
  namdong: { label: '인천 남동구 남동공단', lat: 37.4085, lng: 126.6957 },
}

export const INCHEON_DEFAULT_CATEGORY: BusinessCategory = 'cafe'

export const FORBIDDEN_RESULT_TERMS = [
  '추천',
  '적합',
  '성공 가능',
  '창업하기 좋음',
  '유망',
  '권장',
] as const

export const INCHEON_PUBLIC_DATA_SOURCES: IncheonDataSource[] = [
  {
    sourceId: 'store-small-business',
    name: '소상공인 상가정보',
    provider: '소상공인시장진흥공단',
    url: 'https://www.data.go.kr/data/15083033/fileData.do?recommendDataYn=Y',
    license: '공공데이터포털 제공 조건',
    costFree: true,
    updateCycle: '분기',
    dataPeriod: '2025-12 후보',
    granularity: ['radius_500m'],
    scoringUse: true,
    status: 'planned',
    notes: '인천 CSV 확보 후 H3 10, 반경 500m 동종업종 밀집도 산정',
  },
  {
    sourceId: 'incheon-bus-stops',
    name: '인천 시내버스 정류소 현황',
    provider: '인천광역시',
    url: 'https://www.data.go.kr/data/15074309/fileData.do',
    license: '공공데이터포털 제공 조건',
    costFree: true,
    updateCycle: '반기',
    dataPeriod: '2026-03 후보',
    granularity: ['radius_500m'],
    scoringUse: true,
    status: 'ready',
    notes: '정류소 위치 데이터. 필요 시 전국 버스정류장 위치정보를 보조 후보로 사용',
  },
  {
    sourceId: 'incheon-bus-ridership',
    name: '인천 정류장별 이용승객 현황',
    provider: '인천광역시',
    url: 'https://www.data.go.kr/data/15048264/fileData.do',
    license: '공공데이터포털 제공 조건',
    costFree: true,
    updateCycle: '월간',
    dataPeriod: '2026-03 후보',
    granularity: ['radius_500m'],
    scoringUse: true,
    status: 'ready',
    notes: 'data/bus/incheon/ridership_2025.csv 로컬 후보 확인',
  },
  {
    sourceId: 'incheon-subway-ridership',
    name: '인천교통공사 역별 수송인원',
    provider: '인천교통공사',
    url: 'https://www.data.go.kr/data/15060441/fileData.do',
    license: '공공데이터포털 제공 조건',
    costFree: true,
    updateCycle: '연간',
    dataPeriod: '2025 후보',
    granularity: ['radius_500m'],
    scoringUse: true,
    status: 'ready',
    notes: 'data/subway/incheon/stations.csv 및 data/판단 원천 후보 확인',
  },
  {
    sourceId: 'school-location-standard',
    name: '전국초중등학교위치표준데이터',
    provider: '한국지방교육행정연구재단',
    url: 'https://www.data.go.kr/data/15021148/standard.do?recommendDataYn=Y',
    license: '공공데이터포털 제공 조건',
    costFree: true,
    updateCycle: '반기',
    dataPeriod: '2026 후보',
    granularity: ['radius_500m'],
    scoringUse: false,
    status: 'planned',
    notes: '학교 위치 기준. 학생수는 인천교육청 학교현황과 조인',
  },
  {
    sourceId: 'incheon-school-status',
    name: '인천교육청 학교현황',
    provider: '인천광역시교육청',
    url: 'https://www.data.go.kr/data/15004947/fileData.do',
    license: '공공데이터포털 제공 조건',
    costFree: true,
    updateCycle: '연간',
    dataPeriod: '2026 후보',
    granularity: ['admin_dong_reference', 'radius_500m'],
    scoringUse: false,
    status: 'planned',
    notes: '학생 규모 산정용. 위치 데이터와 조인 필요',
  },
  {
    sourceId: 'childcare-basic',
    name: '어린이집 기본정보',
    provider: '보건복지부',
    url: 'https://www.data.go.kr/data/15101154/openapi.do',
    license: '공공데이터포털 제공 조건',
    costFree: true,
    updateCycle: '수시',
    dataPeriod: 'API 기준',
    granularity: ['radius_500m'],
    scoringUse: false,
    status: 'ready',
    notes: 'API 인증키 필요 가능. 위도, 경도, 정원, 현원, 입소대기 활용',
  },
  {
    sourceId: 'resident-age-admin-dong',
    name: '행정동별 성별·연령별 주민등록 인구',
    provider: '행정안전부',
    url: 'https://www.data.go.kr/data/15097972/fileData.do',
    license: '공공데이터포털 제공 조건',
    costFree: true,
    updateCycle: '월간',
    dataPeriod: '2026 후보',
    granularity: ['admin_dong_reference'],
    scoringUse: false,
    status: 'planned',
    notes: '행정동 참고 지표. H3 500m 사실로 표현하지 않음',
  },
  {
    sourceId: 'reb-small-rent',
    name: '한국부동산원 소규모상가 임대료',
    provider: '한국부동산원',
    url: 'https://www.reb.or.kr/r-one/portal/stat/easyStatPage/T248223134698125.do',
    license: '공공 통계 활용',
    costFree: true,
    updateCycle: '분기',
    dataPeriod: '2025Q4',
    granularity: ['regional_reference'],
    scoringUse: true,
    status: 'ready',
    notes: 'R-ONE 지역별 소규모상가 임대료 표를 원천 JSON으로 저장. 점포 단위 임대료로 표현하지 않음',
  },
  {
    sourceId: 'reb-small-vacancy',
    name: '한국부동산원 소규모상가 공실률',
    provider: '한국부동산원',
    url: 'https://www.reb.or.kr/r-one/portal/stat/easyStatPage/T241833134686576.do',
    license: '공공 통계 활용',
    costFree: true,
    updateCycle: '분기',
    dataPeriod: '2025Q4',
    granularity: ['regional_reference'],
    scoringUse: true,
    status: 'ready',
    notes: 'R-ONE 지역별 소규모상가 공실률 표를 원천 JSON으로 저장. 개별 점포 공실로 표현하지 않음',
  },
  {
    sourceId: 'admin-boundaries',
    name: '행정동·시군구 경계 데이터',
    provider: '국가데이터처',
    url: 'https://www.data.go.kr/data/15129688/fileData.do',
    license: '공공데이터 제공 조건',
    costFree: true,
    updateCycle: '반기',
    dataPeriod: '2026 후보',
    granularity: ['admin_dong_reference', 'district_reference'],
    scoringUse: false,
    status: 'planned',
    notes: '행정동/구군 참고 지표 매칭용',
  },
  {
    sourceId: 'osm-noncommercial-mask',
    name: 'OpenStreetMap 공원·수면 보정 레이어',
    provider: 'OpenStreetMap contributors',
    url: 'https://www.openstreetmap.org/copyright',
    license: 'ODbL',
    costFree: true,
    updateCycle: '수시',
    dataPeriod: 'Overpass API 수집 시점',
    granularity: ['radius_500m'],
    scoringUse: false,
    status: 'planned',
    notes: '공원·수면 등 비상권 셀 마스킹 보조에만 사용하며 점수 산식에는 포함하지 않음',
  },
]
